# Generated by Django 4.0.2 on 2022-02-13 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LaptopAssesories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('image_url', models.URLField(null=True)),
                ('category', models.CharField(choices=[('storage', 'Storage'), ('chargers', 'Chargers'), ('keyboard', 'Keyboard'), ('mouse', 'Mouse'), ('laptop_screens', 'Laptop Screens')], default='storage', max_length=35)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='OtherElectronics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('image_url', models.URLField(null=True)),
                ('category', models.CharField(choices=[('extensions', 'Extensions'), ('bulbs', 'Bulbs'), ('subwoofers', 'Sub Woofers'), ('bulb_holders', 'Bulb Holders'), ('bed_switch', 'Bed Switch')], default='bulb', max_length=35)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhoneAssesories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('image_url', models.URLField(null=True)),
                ('category', models.CharField(choices=[('storage', 'Storage Devices'), ('cables', 'Cables'), ('chargers', 'Chargers'), ('earphones', 'Earphones')], default='cables', max_length=35)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('image_url', models.URLField(null=True)),
                ('category', models.CharField(choices=[('drama', 'Drama'), ('horror', 'Horror'), ('scifi', 'Sci-Fi'), ('action', 'Action'), ('epic', 'Horror'), ('investigative', 'Investigative'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('animation', 'Animation')], default='action', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SingleMovies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
                ('description', models.CharField(max_length=250)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('image_url', models.URLField(null=True)),
                ('category', models.CharField(choices=[('drama', 'Drama'), ('horror', 'Horror'), ('scifi', 'Sci-Fi'), ('action', 'Action'), ('epic', 'Horror'), ('investigative', 'Investigative'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('comedy', 'Comedy'), ('animation', 'Animation')], default='action', max_length=25)),
            ],
        ),
    ]
